steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vaulted-cove-378003/test-project-demo:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vaulted-cove-378003/test-project-demo:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'vaulted-cove-378003', '--region=asia-southeast1', '--platform=managed', '--image=gcr.io/vaulted-cove-378003/test-project-demo:$SHORT_SHA']
