steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vaulted-cove-378003/test-project-demo:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/vaulted-cove-378003/test-project-demo:$SHORT_SHA']
